version: '2'
services:
    newgct-app:
        image: newgct
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://newgct-mysql:3306/newgct?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://newgct-elasticsearch:9200
        ports:
            - 8080:8080
    newgct-mysql:
        extends:
            file: mysql.yml
            service: newgct-mysql
    newgct-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: newgct-elasticsearch
